services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
#      - ./storage:/var/www/html/storage
#      - ./database:/var/www/html/database
    networks:
      - laravel

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

##   Redis (for caching and queues)
#  redis:
#    image: redis:alpine
#    container_name: laravel_redis
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    networks:
#      - laravel
#
##   Queue Worker
#  queue:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: laravel_queue
#    restart: unless-stopped
#    working_dir: /var/www/html
#    command: php artisan queue:work --tries=3 --timeout=90
#    volumes:
#      - ./:/var/www/html
#      - ./storage:/var/www/html/storage
#      - ./database:/var/www/html/database
#    networks:
#      - laravel
#    depends_on:
#      - app
#      - redis
#
##   Scheduler (Cron)
#  scheduler:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: laravel_scheduler
#    restart: unless-stopped
#    working_dir: /var/www/html
#    command: >
#      sh -c "while true; do
#        php artisan schedule:run --verbose --no-interaction &
#        sleep 60
#      done"
#    volumes:
#      - ./:/var/www/html
#      - ./storage:/var/www/html/storage
#      - ./database:/var/www/html/database
#    networks:
#      - laravel
#    depends_on:
#      - app

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
  storage:
  database:
